/**
 * Flowtype definitions for Either
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 */

import * as $protobuf from "protobufjs";
export interface IEitherAny {
  type_url?: string | null;
  value?: Uint8Array | null;
}
declare export class EitherAny mixins IEitherAny {
  constructor(properties?: IEitherAny): this;
  type_url: string;
  value: Uint8Array;
  static create(properties?: IEitherAny): EitherAny;
  static encode(
    message: IEitherAny,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: IEitherAny,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): EitherAny;
  static decodeDelimited(reader: $protobuf.Reader | Uint8Array): EitherAny;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): EitherAny;
  static toObject(
    message: EitherAny,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}
export interface IEitherError {
  messages?: string[] | null;
}
declare export class EitherError mixins IEitherError {
  constructor(properties?: IEitherError): this;
  messages: string[];
  static create(properties?: IEitherError): EitherError;
  static encode(
    message: IEitherError,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: IEitherError,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): EitherError;
  static decodeDelimited(reader: $protobuf.Reader | Uint8Array): EitherError;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): EitherError;
  static toObject(
    message: EitherError,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}
export interface IEitherSuccess {
  response?: IEitherAny | null;
}
declare export class EitherSuccess mixins IEitherSuccess {
  constructor(properties?: IEitherSuccess): this;
  response?: IEitherAny | null;
  static create(properties?: IEitherSuccess): EitherSuccess;
  static encode(
    message: IEitherSuccess,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: IEitherSuccess,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): EitherSuccess;
  static decodeDelimited(reader: $protobuf.Reader | Uint8Array): EitherSuccess;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): EitherSuccess;
  static toObject(
    message: EitherSuccess,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}
export interface IEither {
  error?: IEitherError | null;
  success?: IEitherSuccess | null;
}
declare export class Either mixins IEither {
  constructor(properties?: IEither): this;
  error?: IEitherError | null;
  success?: IEitherSuccess | null;
  content?: "error" | "success";
  static create(properties?: IEither): Either;
  static encode(message: IEither, writer?: $protobuf.Writer): $protobuf.Writer;
  static encodeDelimited(
    message: IEither,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(reader: $protobuf.Reader | Uint8Array, length?: number): Either;
  static decodeDelimited(reader: $protobuf.Reader | Uint8Array): Either;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): Either;
  static toObject(
    message: Either,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}
declare var scalapb: typeof npm$namespace$scalapb;

declare var npm$namespace$scalapb: {|
  MessageOptions: typeof scalapb$MessageOptions,
  FieldOptions: typeof scalapb$FieldOptions,
  EnumOptions: typeof scalapb$EnumOptions,
  EnumValueOptions: typeof scalapb$EnumValueOptions,
  OneofOptions: typeof scalapb$OneofOptions,
  ScalaPbOptions: typeof npm$namespace$scalapb$ScalaPbOptions
|};
declare interface scalapb$IScalaPbOptions {
  package_name?: string | null;
  flat_package?: boolean | null;
  import?: string[] | null;
  preamble?: string[] | null;
  single_file?: boolean | null;
  no_primitive_wrappers?: boolean | null;
  primitive_wrappers?: boolean | null;
  collection_type?: string | null;
  preserve_unknown_fields?: boolean | null;
  object_name?: string | null;
  scope?: $Values<typeof scalapb$ScalaPbOptions$OptionsScope> | null;
  lenses?: boolean | null;
  retain_source_code_info?: boolean | null;
  map_type?: string | null;
  test_only_no_java_conversions?: boolean | null;
}

declare class scalapb$ScalaPbOptions mixins scalapb$IScalaPbOptions {
  constructor(properties?: scalapb$IScalaPbOptions): this;
  package_name: string;
  flat_package: boolean;
  import: string[];
  preamble: string[];
  single_file: boolean;
  no_primitive_wrappers: boolean;
  primitive_wrappers: boolean;
  collection_type: string;
  preserve_unknown_fields: boolean;
  object_name: string;
  scope: $Values<typeof scalapb$ScalaPbOptions$OptionsScope>;
  lenses: boolean;
  retain_source_code_info: boolean;
  map_type: string;
  test_only_no_java_conversions: boolean;
  static create(properties?: scalapb$IScalaPbOptions): scalapb$ScalaPbOptions;
  static encode(
    message: scalapb$IScalaPbOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: scalapb$IScalaPbOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): scalapb$ScalaPbOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): scalapb$ScalaPbOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): scalapb$ScalaPbOptions;
  static toObject(
    message: scalapb$ScalaPbOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$scalapb$ScalaPbOptions: {|
  OptionsScope: typeof scalapb$ScalaPbOptions$OptionsScope
|};

declare var scalapb$ScalaPbOptions$OptionsScope: {|
  +FILE: 0, // 0
  +PACKAGE: 1 // 1
|};

declare interface scalapb$IMessageOptions {
  extends?: string[] | null;
  companion_extends?: string[] | null;
  annotations?: string[] | null;
  type?: string | null;
  companion_annotations?: string[] | null;
  sealed_oneof_extends?: string[] | null;
}

declare class scalapb$MessageOptions mixins scalapb$IMessageOptions {
  constructor(properties?: scalapb$IMessageOptions): this;
  extends: string[];
  companion_extends: string[];
  annotations: string[];
  type: string;
  companion_annotations: string[];
  sealed_oneof_extends: string[];
  static create(properties?: scalapb$IMessageOptions): scalapb$MessageOptions;
  static encode(
    message: scalapb$IMessageOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: scalapb$IMessageOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): scalapb$MessageOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): scalapb$MessageOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): scalapb$MessageOptions;
  static toObject(
    message: scalapb$MessageOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface scalapb$IFieldOptions {
  type?: string | null;
  scala_name?: string | null;
  collection_type?: string | null;
  key_type?: string | null;
  value_type?: string | null;
  annotations?: string[] | null;
  map_type?: string | null;
  no_box?: boolean | null;
}

declare class scalapb$FieldOptions mixins scalapb$IFieldOptions {
  constructor(properties?: scalapb$IFieldOptions): this;
  type: string;
  scala_name: string;
  collection_type: string;
  key_type: string;
  value_type: string;
  annotations: string[];
  map_type: string;
  no_box: boolean;
  static create(properties?: scalapb$IFieldOptions): scalapb$FieldOptions;
  static encode(
    message: scalapb$IFieldOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: scalapb$IFieldOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): scalapb$FieldOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): scalapb$FieldOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): scalapb$FieldOptions;
  static toObject(
    message: scalapb$FieldOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface scalapb$IEnumOptions {
  extends?: string[] | null;
  companion_extends?: string[] | null;
  type?: string | null;
}

declare class scalapb$EnumOptions mixins scalapb$IEnumOptions {
  constructor(properties?: scalapb$IEnumOptions): this;
  extends: string[];
  companion_extends: string[];
  type: string;
  static create(properties?: scalapb$IEnumOptions): scalapb$EnumOptions;
  static encode(
    message: scalapb$IEnumOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: scalapb$IEnumOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): scalapb$EnumOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): scalapb$EnumOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): scalapb$EnumOptions;
  static toObject(
    message: scalapb$EnumOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface scalapb$IEnumValueOptions {
  extends?: string[] | null;
}

declare class scalapb$EnumValueOptions mixins scalapb$IEnumValueOptions {
  constructor(properties?: scalapb$IEnumValueOptions): this;
  extends: string[];
  static create(
    properties?: scalapb$IEnumValueOptions
  ): scalapb$EnumValueOptions;
  static encode(
    message: scalapb$IEnumValueOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: scalapb$IEnumValueOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): scalapb$EnumValueOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): scalapb$EnumValueOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): scalapb$EnumValueOptions;
  static toObject(
    message: scalapb$EnumValueOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface scalapb$IOneofOptions {
  extends?: string[] | null;
}

declare class scalapb$OneofOptions mixins scalapb$IOneofOptions {
  constructor(properties?: scalapb$IOneofOptions): this;
  extends: string[];
  static create(properties?: scalapb$IOneofOptions): scalapb$OneofOptions;
  static encode(
    message: scalapb$IOneofOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: scalapb$IOneofOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): scalapb$OneofOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): scalapb$OneofOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): scalapb$OneofOptions;
  static toObject(
    message: scalapb$OneofOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}
declare var google: typeof npm$namespace$google;

declare var npm$namespace$google: {|
  protobuf: typeof npm$namespace$google$protobuf
|};

declare var npm$namespace$google$protobuf: {|
  FileDescriptorSet: typeof google$protobuf$FileDescriptorSet,
  FileDescriptorProto: typeof google$protobuf$FileDescriptorProto,
  OneofDescriptorProto: typeof google$protobuf$OneofDescriptorProto,
  EnumDescriptorProto: typeof google$protobuf$EnumDescriptorProto,
  EnumValueDescriptorProto: typeof google$protobuf$EnumValueDescriptorProto,
  ServiceDescriptorProto: typeof google$protobuf$ServiceDescriptorProto,
  MethodDescriptorProto: typeof google$protobuf$MethodDescriptorProto,
  MessageOptions: typeof google$protobuf$MessageOptions,
  OneofOptions: typeof google$protobuf$OneofOptions,
  EnumOptions: typeof google$protobuf$EnumOptions,
  EnumValueOptions: typeof google$protobuf$EnumValueOptions,
  ServiceOptions: typeof google$protobuf$ServiceOptions,
  MethodOptions: typeof google$protobuf$MethodOptions,
  Any: typeof google$protobuf$Any,
  DescriptorProto: typeof npm$namespace$google$protobuf$DescriptorProto,
  FieldDescriptorProto: typeof npm$namespace$google$protobuf$FieldDescriptorProto,
  FileOptions: typeof npm$namespace$google$protobuf$FileOptions,
  FieldOptions: typeof npm$namespace$google$protobuf$FieldOptions,
  UninterpretedOption: typeof npm$namespace$google$protobuf$UninterpretedOption,
  SourceCodeInfo: typeof npm$namespace$google$protobuf$SourceCodeInfo,
  GeneratedCodeInfo: typeof npm$namespace$google$protobuf$GeneratedCodeInfo
|};
declare interface google$protobuf$IFileDescriptorSet {
  file?: google$protobuf$IFileDescriptorProto[] | null;
}

declare class google$protobuf$FileDescriptorSet
  mixins google$protobuf$IFileDescriptorSet {
  constructor(properties?: google$protobuf$IFileDescriptorSet): this;
  file: google$protobuf$IFileDescriptorProto[];
  static create(
    properties?: google$protobuf$IFileDescriptorSet
  ): google$protobuf$FileDescriptorSet;
  static encode(
    message: google$protobuf$IFileDescriptorSet,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IFileDescriptorSet,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$FileDescriptorSet;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$FileDescriptorSet;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$FileDescriptorSet;
  static toObject(
    message: google$protobuf$FileDescriptorSet,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IFileDescriptorProto {
  name?: string | null;
  package?: string | null;
  dependency?: string[] | null;
  public_dependency?: number[] | null;
  weak_dependency?: number[] | null;
  message_type?: google$protobuf$IDescriptorProto[] | null;
  enum_type?: google$protobuf$IEnumDescriptorProto[] | null;
  service?: google$protobuf$IServiceDescriptorProto[] | null;
  extension?: google$protobuf$IFieldDescriptorProto[] | null;
  options?: google$protobuf$IFileOptions | null;
  source_code_info?: google$protobuf$ISourceCodeInfo | null;
  syntax?: string | null;
}

declare class google$protobuf$FileDescriptorProto
  mixins google$protobuf$IFileDescriptorProto {
  constructor(properties?: google$protobuf$IFileDescriptorProto): this;
  name: string;
  package: string;
  dependency: string[];
  public_dependency: number[];
  weak_dependency: number[];
  message_type: google$protobuf$IDescriptorProto[];
  enum_type: google$protobuf$IEnumDescriptorProto[];
  service: google$protobuf$IServiceDescriptorProto[];
  extension: google$protobuf$IFieldDescriptorProto[];
  options?: google$protobuf$IFileOptions | null;
  source_code_info?: google$protobuf$ISourceCodeInfo | null;
  syntax: string;
  static create(
    properties?: google$protobuf$IFileDescriptorProto
  ): google$protobuf$FileDescriptorProto;
  static encode(
    message: google$protobuf$IFileDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IFileDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$FileDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$FileDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$FileDescriptorProto;
  static toObject(
    message: google$protobuf$FileDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IDescriptorProto {
  name?: string | null;
  field?: google$protobuf$IFieldDescriptorProto[] | null;
  extension?: google$protobuf$IFieldDescriptorProto[] | null;
  nested_type?: google$protobuf$IDescriptorProto[] | null;
  enum_type?: google$protobuf$IEnumDescriptorProto[] | null;
  extension_range?: google$protobuf$DescriptorProto$IExtensionRange[] | null;
  oneof_decl?: google$protobuf$IOneofDescriptorProto[] | null;
  options?: google$protobuf$IMessageOptions | null;
  reserved_range?: google$protobuf$DescriptorProto$IReservedRange[] | null;
  reserved_name?: string[] | null;
}

declare class google$protobuf$DescriptorProto
  mixins google$protobuf$IDescriptorProto {
  constructor(properties?: google$protobuf$IDescriptorProto): this;
  name: string;
  field: google$protobuf$IFieldDescriptorProto[];
  extension: google$protobuf$IFieldDescriptorProto[];
  nested_type: google$protobuf$IDescriptorProto[];
  enum_type: google$protobuf$IEnumDescriptorProto[];
  extension_range: google$protobuf$DescriptorProto$IExtensionRange[];
  oneof_decl: google$protobuf$IOneofDescriptorProto[];
  options?: google$protobuf$IMessageOptions | null;
  reserved_range: google$protobuf$DescriptorProto$IReservedRange[];
  reserved_name: string[];
  static create(
    properties?: google$protobuf$IDescriptorProto
  ): google$protobuf$DescriptorProto;
  static encode(
    message: google$protobuf$IDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$DescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$DescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$DescriptorProto;
  static toObject(
    message: google$protobuf$DescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$DescriptorProto: {|
  ExtensionRange: typeof google$protobuf$DescriptorProto$ExtensionRange,
  ReservedRange: typeof google$protobuf$DescriptorProto$ReservedRange
|};
declare interface google$protobuf$DescriptorProto$IExtensionRange {
  start?: number | null;
  end?: number | null;
}

declare class google$protobuf$DescriptorProto$ExtensionRange
  mixins google$protobuf$DescriptorProto$IExtensionRange {
  constructor(
    properties?: google$protobuf$DescriptorProto$IExtensionRange
  ): this;
  start: number;
  end: number;
  static create(
    properties?: google$protobuf$DescriptorProto$IExtensionRange
  ): google$protobuf$DescriptorProto$ExtensionRange;
  static encode(
    message: google$protobuf$DescriptorProto$IExtensionRange,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$DescriptorProto$IExtensionRange,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$DescriptorProto$ExtensionRange;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$DescriptorProto$ExtensionRange;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$DescriptorProto$ExtensionRange;
  static toObject(
    message: google$protobuf$DescriptorProto$ExtensionRange,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$DescriptorProto$IReservedRange {
  start?: number | null;
  end?: number | null;
}

declare class google$protobuf$DescriptorProto$ReservedRange
  mixins google$protobuf$DescriptorProto$IReservedRange {
  constructor(
    properties?: google$protobuf$DescriptorProto$IReservedRange
  ): this;
  start: number;
  end: number;
  static create(
    properties?: google$protobuf$DescriptorProto$IReservedRange
  ): google$protobuf$DescriptorProto$ReservedRange;
  static encode(
    message: google$protobuf$DescriptorProto$IReservedRange,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$DescriptorProto$IReservedRange,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$DescriptorProto$ReservedRange;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$DescriptorProto$ReservedRange;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$DescriptorProto$ReservedRange;
  static toObject(
    message: google$protobuf$DescriptorProto$ReservedRange,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IFieldDescriptorProto {
  name?: string | null;
  number?: number | null;
  label?: $Values<typeof google$protobuf$FieldDescriptorProto$Label> | null;
  type?: $Values<typeof google$protobuf$FieldDescriptorProto$Type> | null;
  type_name?: string | null;
  extendee?: string | null;
  default_value?: string | null;
  oneof_index?: number | null;
  json_name?: string | null;
  options?: google$protobuf$IFieldOptions | null;
}

declare class google$protobuf$FieldDescriptorProto
  mixins google$protobuf$IFieldDescriptorProto {
  constructor(properties?: google$protobuf$IFieldDescriptorProto): this;
  name: string;
  number: number;
  label: $Values<typeof google$protobuf$FieldDescriptorProto$Label>;
  type: $Values<typeof google$protobuf$FieldDescriptorProto$Type>;
  type_name: string;
  extendee: string;
  default_value: string;
  oneof_index: number;
  json_name: string;
  options?: google$protobuf$IFieldOptions | null;
  static create(
    properties?: google$protobuf$IFieldDescriptorProto
  ): google$protobuf$FieldDescriptorProto;
  static encode(
    message: google$protobuf$IFieldDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IFieldDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$FieldDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$FieldDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$FieldDescriptorProto;
  static toObject(
    message: google$protobuf$FieldDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$FieldDescriptorProto: {|
  Type: typeof google$protobuf$FieldDescriptorProto$Type,
  Label: typeof google$protobuf$FieldDescriptorProto$Label
|};

declare var google$protobuf$FieldDescriptorProto$Type: {|
  +TYPE_DOUBLE: 1, // 1
  +TYPE_FLOAT: 2, // 2
  +TYPE_INT64: 3, // 3
  +TYPE_UINT64: 4, // 4
  +TYPE_INT32: 5, // 5
  +TYPE_FIXED64: 6, // 6
  +TYPE_FIXED32: 7, // 7
  +TYPE_BOOL: 8, // 8
  +TYPE_STRING: 9, // 9
  +TYPE_GROUP: 10, // 10
  +TYPE_MESSAGE: 11, // 11
  +TYPE_BYTES: 12, // 12
  +TYPE_UINT32: 13, // 13
  +TYPE_ENUM: 14, // 14
  +TYPE_SFIXED32: 15, // 15
  +TYPE_SFIXED64: 16, // 16
  +TYPE_SINT32: 17, // 17
  +TYPE_SINT64: 18 // 18
|};

declare var google$protobuf$FieldDescriptorProto$Label: {|
  +LABEL_OPTIONAL: 1, // 1
  +LABEL_REQUIRED: 2, // 2
  +LABEL_REPEATED: 3 // 3
|};

declare interface google$protobuf$IOneofDescriptorProto {
  name?: string | null;
  options?: google$protobuf$IOneofOptions | null;
}

declare class google$protobuf$OneofDescriptorProto
  mixins google$protobuf$IOneofDescriptorProto {
  constructor(properties?: google$protobuf$IOneofDescriptorProto): this;
  name: string;
  options?: google$protobuf$IOneofOptions | null;
  static create(
    properties?: google$protobuf$IOneofDescriptorProto
  ): google$protobuf$OneofDescriptorProto;
  static encode(
    message: google$protobuf$IOneofDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IOneofDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$OneofDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$OneofDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$OneofDescriptorProto;
  static toObject(
    message: google$protobuf$OneofDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IEnumDescriptorProto {
  name?: string | null;
  value?: google$protobuf$IEnumValueDescriptorProto[] | null;
  options?: google$protobuf$IEnumOptions | null;
}

declare class google$protobuf$EnumDescriptorProto
  mixins google$protobuf$IEnumDescriptorProto {
  constructor(properties?: google$protobuf$IEnumDescriptorProto): this;
  name: string;
  value: google$protobuf$IEnumValueDescriptorProto[];
  options?: google$protobuf$IEnumOptions | null;
  static create(
    properties?: google$protobuf$IEnumDescriptorProto
  ): google$protobuf$EnumDescriptorProto;
  static encode(
    message: google$protobuf$IEnumDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IEnumDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$EnumDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$EnumDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$EnumDescriptorProto;
  static toObject(
    message: google$protobuf$EnumDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IEnumValueDescriptorProto {
  name?: string | null;
  number?: number | null;
  options?: google$protobuf$IEnumValueOptions | null;
}

declare class google$protobuf$EnumValueDescriptorProto
  mixins google$protobuf$IEnumValueDescriptorProto {
  constructor(properties?: google$protobuf$IEnumValueDescriptorProto): this;
  name: string;
  number: number;
  options?: google$protobuf$IEnumValueOptions | null;
  static create(
    properties?: google$protobuf$IEnumValueDescriptorProto
  ): google$protobuf$EnumValueDescriptorProto;
  static encode(
    message: google$protobuf$IEnumValueDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IEnumValueDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$EnumValueDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$EnumValueDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$EnumValueDescriptorProto;
  static toObject(
    message: google$protobuf$EnumValueDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IServiceDescriptorProto {
  name?: string | null;
  method?: google$protobuf$IMethodDescriptorProto[] | null;
  options?: google$protobuf$IServiceOptions | null;
}

declare class google$protobuf$ServiceDescriptorProto
  mixins google$protobuf$IServiceDescriptorProto {
  constructor(properties?: google$protobuf$IServiceDescriptorProto): this;
  name: string;
  method: google$protobuf$IMethodDescriptorProto[];
  options?: google$protobuf$IServiceOptions | null;
  static create(
    properties?: google$protobuf$IServiceDescriptorProto
  ): google$protobuf$ServiceDescriptorProto;
  static encode(
    message: google$protobuf$IServiceDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IServiceDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$ServiceDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$ServiceDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$ServiceDescriptorProto;
  static toObject(
    message: google$protobuf$ServiceDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IMethodDescriptorProto {
  name?: string | null;
  input_type?: string | null;
  output_type?: string | null;
  options?: google$protobuf$IMethodOptions | null;
  client_streaming?: boolean | null;
  server_streaming?: boolean | null;
}

declare class google$protobuf$MethodDescriptorProto
  mixins google$protobuf$IMethodDescriptorProto {
  constructor(properties?: google$protobuf$IMethodDescriptorProto): this;
  name: string;
  input_type: string;
  output_type: string;
  options?: google$protobuf$IMethodOptions | null;
  client_streaming: boolean;
  server_streaming: boolean;
  static create(
    properties?: google$protobuf$IMethodDescriptorProto
  ): google$protobuf$MethodDescriptorProto;
  static encode(
    message: google$protobuf$IMethodDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IMethodDescriptorProto,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$MethodDescriptorProto;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$MethodDescriptorProto;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$MethodDescriptorProto;
  static toObject(
    message: google$protobuf$MethodDescriptorProto,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IFileOptions {
  java_package?: string | null;
  java_outer_classname?: string | null;
  java_multiple_files?: boolean | null;
  java_generate_equals_and_hash?: boolean | null;
  java_string_check_utf8?: boolean | null;
  optimize_for?: $Values<
    typeof google$protobuf$FileOptions$OptimizeMode
  > | null;
  go_package?: string | null;
  cc_generic_services?: boolean | null;
  java_generic_services?: boolean | null;
  py_generic_services?: boolean | null;
  deprecated?: boolean | null;
  cc_enable_arenas?: boolean | null;
  objc_class_prefix?: string | null;
  csharp_namespace?: string | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
  ".scalapb.options"?: scalapb$IScalaPbOptions | null;
}

declare class google$protobuf$FileOptions mixins google$protobuf$IFileOptions {
  constructor(properties?: google$protobuf$IFileOptions): this;
  java_package: string;
  java_outer_classname: string;
  java_multiple_files: boolean;
  java_generate_equals_and_hash: boolean;
  java_string_check_utf8: boolean;
  optimize_for: $Values<typeof google$protobuf$FileOptions$OptimizeMode>;
  go_package: string;
  cc_generic_services: boolean;
  java_generic_services: boolean;
  py_generic_services: boolean;
  deprecated: boolean;
  cc_enable_arenas: boolean;
  objc_class_prefix: string;
  csharp_namespace: string;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IFileOptions
  ): google$protobuf$FileOptions;
  static encode(
    message: google$protobuf$IFileOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IFileOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$FileOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$FileOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$FileOptions;
  static toObject(
    message: google$protobuf$FileOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$FileOptions: {|
  OptimizeMode: typeof google$protobuf$FileOptions$OptimizeMode
|};

declare var google$protobuf$FileOptions$OptimizeMode: {|
  +SPEED: 1, // 1
  +CODE_SIZE: 2, // 2
  +LITE_RUNTIME: 3 // 3
|};

declare interface google$protobuf$IMessageOptions {
  message_set_wire_format?: boolean | null;
  no_standard_descriptor_accessor?: boolean | null;
  deprecated?: boolean | null;
  map_entry?: boolean | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
  ".scalapb.message"?: scalapb$IMessageOptions | null;
}

declare class google$protobuf$MessageOptions
  mixins google$protobuf$IMessageOptions {
  constructor(properties?: google$protobuf$IMessageOptions): this;
  message_set_wire_format: boolean;
  no_standard_descriptor_accessor: boolean;
  deprecated: boolean;
  map_entry: boolean;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IMessageOptions
  ): google$protobuf$MessageOptions;
  static encode(
    message: google$protobuf$IMessageOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IMessageOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$MessageOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$MessageOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$MessageOptions;
  static toObject(
    message: google$protobuf$MessageOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IFieldOptions {
  ctype?: $Values<typeof google$protobuf$FieldOptions$CType> | null;
  packed?: boolean | null;
  jstype?: $Values<typeof google$protobuf$FieldOptions$JSType> | null;
  lazy?: boolean | null;
  deprecated?: boolean | null;
  weak?: boolean | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
  ".scalapb.field"?: scalapb$IFieldOptions | null;
}

declare class google$protobuf$FieldOptions
  mixins google$protobuf$IFieldOptions {
  constructor(properties?: google$protobuf$IFieldOptions): this;
  ctype: $Values<typeof google$protobuf$FieldOptions$CType>;
  packed: boolean;
  jstype: $Values<typeof google$protobuf$FieldOptions$JSType>;
  lazy: boolean;
  deprecated: boolean;
  weak: boolean;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IFieldOptions
  ): google$protobuf$FieldOptions;
  static encode(
    message: google$protobuf$IFieldOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IFieldOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$FieldOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$FieldOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$FieldOptions;
  static toObject(
    message: google$protobuf$FieldOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$FieldOptions: {|
  CType: typeof google$protobuf$FieldOptions$CType,
  JSType: typeof google$protobuf$FieldOptions$JSType
|};

declare var google$protobuf$FieldOptions$CType: {|
  +STRING: 0, // 0
  +CORD: 1, // 1
  +STRING_PIECE: 2 // 2
|};

declare var google$protobuf$FieldOptions$JSType: {|
  +JS_NORMAL: 0, // 0
  +JS_STRING: 1, // 1
  +JS_NUMBER: 2 // 2
|};

declare interface google$protobuf$IOneofOptions {
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
  ".scalapb.oneof"?: scalapb$IOneofOptions | null;
}

declare class google$protobuf$OneofOptions
  mixins google$protobuf$IOneofOptions {
  constructor(properties?: google$protobuf$IOneofOptions): this;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IOneofOptions
  ): google$protobuf$OneofOptions;
  static encode(
    message: google$protobuf$IOneofOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IOneofOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$OneofOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$OneofOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$OneofOptions;
  static toObject(
    message: google$protobuf$OneofOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IEnumOptions {
  allow_alias?: boolean | null;
  deprecated?: boolean | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
  ".scalapb.enum_options"?: scalapb$IEnumOptions | null;
}

declare class google$protobuf$EnumOptions mixins google$protobuf$IEnumOptions {
  constructor(properties?: google$protobuf$IEnumOptions): this;
  allow_alias: boolean;
  deprecated: boolean;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IEnumOptions
  ): google$protobuf$EnumOptions;
  static encode(
    message: google$protobuf$IEnumOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IEnumOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$EnumOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$EnumOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$EnumOptions;
  static toObject(
    message: google$protobuf$EnumOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IEnumValueOptions {
  deprecated?: boolean | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
  ".scalapb.enum_value"?: scalapb$IEnumValueOptions | null;
}

declare class google$protobuf$EnumValueOptions
  mixins google$protobuf$IEnumValueOptions {
  constructor(properties?: google$protobuf$IEnumValueOptions): this;
  deprecated: boolean;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IEnumValueOptions
  ): google$protobuf$EnumValueOptions;
  static encode(
    message: google$protobuf$IEnumValueOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IEnumValueOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$EnumValueOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$EnumValueOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$EnumValueOptions;
  static toObject(
    message: google$protobuf$EnumValueOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IServiceOptions {
  deprecated?: boolean | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
}

declare class google$protobuf$ServiceOptions
  mixins google$protobuf$IServiceOptions {
  constructor(properties?: google$protobuf$IServiceOptions): this;
  deprecated: boolean;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IServiceOptions
  ): google$protobuf$ServiceOptions;
  static encode(
    message: google$protobuf$IServiceOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IServiceOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$ServiceOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$ServiceOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$ServiceOptions;
  static toObject(
    message: google$protobuf$ServiceOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IMethodOptions {
  deprecated?: boolean | null;
  uninterpreted_option?: google$protobuf$IUninterpretedOption[] | null;
}

declare class google$protobuf$MethodOptions
  mixins google$protobuf$IMethodOptions {
  constructor(properties?: google$protobuf$IMethodOptions): this;
  deprecated: boolean;
  uninterpreted_option: google$protobuf$IUninterpretedOption[];
  static create(
    properties?: google$protobuf$IMethodOptions
  ): google$protobuf$MethodOptions;
  static encode(
    message: google$protobuf$IMethodOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IMethodOptions,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$MethodOptions;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$MethodOptions;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$MethodOptions;
  static toObject(
    message: google$protobuf$MethodOptions,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IUninterpretedOption {
  name?: google$protobuf$UninterpretedOption$INamePart[] | null;
  identifier_value?: string | null;
  positive_int_value?: number | Long | null;
  negative_int_value?: number | Long | null;
  double_value?: number | null;
  string_value?: Uint8Array | null;
  aggregate_value?: string | null;
}

declare class google$protobuf$UninterpretedOption
  mixins google$protobuf$IUninterpretedOption {
  constructor(properties?: google$protobuf$IUninterpretedOption): this;
  name: google$protobuf$UninterpretedOption$INamePart[];
  identifier_value: string;
  positive_int_value: number | Long;
  negative_int_value: number | Long;
  double_value: number;
  string_value: Uint8Array;
  aggregate_value: string;
  static create(
    properties?: google$protobuf$IUninterpretedOption
  ): google$protobuf$UninterpretedOption;
  static encode(
    message: google$protobuf$IUninterpretedOption,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IUninterpretedOption,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$UninterpretedOption;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$UninterpretedOption;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$UninterpretedOption;
  static toObject(
    message: google$protobuf$UninterpretedOption,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$UninterpretedOption: {|
  NamePart: typeof google$protobuf$UninterpretedOption$NamePart
|};
declare interface google$protobuf$UninterpretedOption$INamePart {
  name_part: string;
  is_extension: boolean;
}

declare class google$protobuf$UninterpretedOption$NamePart
  mixins google$protobuf$UninterpretedOption$INamePart {
  constructor(properties?: google$protobuf$UninterpretedOption$INamePart): this;
  name_part: string;
  is_extension: boolean;
  static create(
    properties?: google$protobuf$UninterpretedOption$INamePart
  ): google$protobuf$UninterpretedOption$NamePart;
  static encode(
    message: google$protobuf$UninterpretedOption$INamePart,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$UninterpretedOption$INamePart,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$UninterpretedOption$NamePart;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$UninterpretedOption$NamePart;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$UninterpretedOption$NamePart;
  static toObject(
    message: google$protobuf$UninterpretedOption$NamePart,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$ISourceCodeInfo {
  location?: google$protobuf$SourceCodeInfo$ILocation[] | null;
}

declare class google$protobuf$SourceCodeInfo
  mixins google$protobuf$ISourceCodeInfo {
  constructor(properties?: google$protobuf$ISourceCodeInfo): this;
  location: google$protobuf$SourceCodeInfo$ILocation[];
  static create(
    properties?: google$protobuf$ISourceCodeInfo
  ): google$protobuf$SourceCodeInfo;
  static encode(
    message: google$protobuf$ISourceCodeInfo,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$ISourceCodeInfo,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$SourceCodeInfo;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$SourceCodeInfo;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$SourceCodeInfo;
  static toObject(
    message: google$protobuf$SourceCodeInfo,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$SourceCodeInfo: {|
  Location: typeof google$protobuf$SourceCodeInfo$Location
|};
declare interface google$protobuf$SourceCodeInfo$ILocation {
  path?: number[] | null;
  span?: number[] | null;
  leading_comments?: string | null;
  trailing_comments?: string | null;
  leading_detached_comments?: string[] | null;
}

declare class google$protobuf$SourceCodeInfo$Location
  mixins google$protobuf$SourceCodeInfo$ILocation {
  constructor(properties?: google$protobuf$SourceCodeInfo$ILocation): this;
  path: number[];
  span: number[];
  leading_comments: string;
  trailing_comments: string;
  leading_detached_comments: string[];
  static create(
    properties?: google$protobuf$SourceCodeInfo$ILocation
  ): google$protobuf$SourceCodeInfo$Location;
  static encode(
    message: google$protobuf$SourceCodeInfo$ILocation,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$SourceCodeInfo$ILocation,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$SourceCodeInfo$Location;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$SourceCodeInfo$Location;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$SourceCodeInfo$Location;
  static toObject(
    message: google$protobuf$SourceCodeInfo$Location,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IGeneratedCodeInfo {
  annotation?: google$protobuf$GeneratedCodeInfo$IAnnotation[] | null;
}

declare class google$protobuf$GeneratedCodeInfo
  mixins google$protobuf$IGeneratedCodeInfo {
  constructor(properties?: google$protobuf$IGeneratedCodeInfo): this;
  annotation: google$protobuf$GeneratedCodeInfo$IAnnotation[];
  static create(
    properties?: google$protobuf$IGeneratedCodeInfo
  ): google$protobuf$GeneratedCodeInfo;
  static encode(
    message: google$protobuf$IGeneratedCodeInfo,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IGeneratedCodeInfo,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$GeneratedCodeInfo;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$GeneratedCodeInfo;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$GeneratedCodeInfo;
  static toObject(
    message: google$protobuf$GeneratedCodeInfo,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare var npm$namespace$google$protobuf$GeneratedCodeInfo: {|
  Annotation: typeof google$protobuf$GeneratedCodeInfo$Annotation
|};
declare interface google$protobuf$GeneratedCodeInfo$IAnnotation {
  path?: number[] | null;
  source_file?: string | null;
  begin?: number | null;
  end?: number | null;
}

declare class google$protobuf$GeneratedCodeInfo$Annotation
  mixins google$protobuf$GeneratedCodeInfo$IAnnotation {
  constructor(properties?: google$protobuf$GeneratedCodeInfo$IAnnotation): this;
  path: number[];
  source_file: string;
  begin: number;
  end: number;
  static create(
    properties?: google$protobuf$GeneratedCodeInfo$IAnnotation
  ): google$protobuf$GeneratedCodeInfo$Annotation;
  static encode(
    message: google$protobuf$GeneratedCodeInfo$IAnnotation,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$GeneratedCodeInfo$IAnnotation,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$GeneratedCodeInfo$Annotation;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$GeneratedCodeInfo$Annotation;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$GeneratedCodeInfo$Annotation;
  static toObject(
    message: google$protobuf$GeneratedCodeInfo$Annotation,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}

declare interface google$protobuf$IAny {
  type_url?: string | null;
  value?: Uint8Array | null;
}

declare class google$protobuf$Any mixins google$protobuf$IAny {
  constructor(properties?: google$protobuf$IAny): this;
  type_url: string;
  value: Uint8Array;
  static create(properties?: google$protobuf$IAny): google$protobuf$Any;
  static encode(
    message: google$protobuf$IAny,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static encodeDelimited(
    message: google$protobuf$IAny,
    writer?: $protobuf.Writer
  ): $protobuf.Writer;
  static decode(
    reader: $protobuf.Reader | Uint8Array,
    length?: number
  ): google$protobuf$Any;
  static decodeDelimited(
    reader: $protobuf.Reader | Uint8Array
  ): google$protobuf$Any;
  static verify(message: {
    [k: string]: any,
    ...
  }): string | null;
  static fromObject(object: {
    [k: string]: any,
    ...
  }): google$protobuf$Any;
  static toObject(
    message: google$protobuf$Any,
    options?: $protobuf.IConversionOptions
  ): {
    [k: string]: any,
    ...
  };
  toJSON(): {
    [k: string]: any,
    ...
  };
}
